zoom: "63.25%"
title: "Théo Michel - Resume"
firstName: "Théo"
lastName: "Michel"
position: "Recent Master's graduate in Software Engineering and Artificial Intelligence."
links:
  - url: "https://github.com/theo-michel"
    icon: "fab fa-github"
  # - url: "https://www.instagram.com/riiswa"
  #   icon: "fab fa-instagram"
  - url: "www.linkedin.com/in/theo-michel42"
    icon: "fab fa-linkedin"
  # - url: "https://warisradji.com"
  #   icon: "fas fa-globe"
details:
  - key: "Age"
    value: "23 years"
  - key: "Languages"
    value: "French, German, English, Spanish"
  - key: "Location"
    value: "Flexible"
  - key: "Phone"
    value: "+33 6 43 45 13 97"
  - key: "E-mail"
    value: "theo64200@gmail.com"
  # - key: "Website"
  #   value: "https://warisradji.com"
  - key: "Interests"
    value: "Classical Music, Science-Fiction, Philosophy, AI, Gym, MMA, Volley-Ball"
description: "Dedicated to enhancing human intelligence through AI, Brain-Computer Interfaces, and Education. I am looking for an Internship in which I can learn from great minds and harness my skills in AI/RL, BCI, and Software Engineering to have a positive impact on the project."
# description: "Dedicated to enhancing human intelligence through AI, Brain Computer Interfaces and Education. I am looking for an internship enabling me to leverage my skills in AI/RL, BCI and Software Engineering in order to make a meaningfull contribution, and at the same time improve skills. " #"I am fascinated by the concept of Intelligence and looking for an opportunity to explore it through Artificial Intelligence, Reinforcement Learning and Brain Computer Interfacing."

jobs:
  - date: "Apr 2022 - Apr 2023"
    company: "Snow GMAO"
    logo: "img/logo/snow-gmao.png"
    arrow: 50
    position: "CO-FOUNDER (with Widad ZIZOUAN) • Val d'Isère"
    description: "Co-founded a startup aimed at simplifying equipment maintenance for small companies using AI, overseeing a team of 9. Went through all the stages of creating a company, and successfully developed a leading-edge app in the field of maintenance."
    badges:
      - name: "Flutter"
        icon: "img/ico/flutter.png"
      - name: "Firebase"
        icon: "img/ico/firebase.png"
      - name: "G Cloud"
        icon: "img/ico/google-cloud.png"
      - name: "ML Kit"
        icon: "img/ico/ml-kit.png"
    link: https://snow-cannon-gmao-website.firebaseapp.com/
    id: snow
  - date: "Aug 2021 - January 2022 "
    company: "Le Connecteur"
    logo: "img/logo/connecteur.png"
    arrow: 50
    position: "LEAD DEVELOPER/ PRODUCT OWNER • Freelance • Biarritz"
    description: "Led a team of five to develop a service for managing coworking space reservations through a WooCommerce site and a Flutter application for QR code scanning. Service has been running smoothly for 2 years."
    badges:
      - name: "Flutter"
        icon: "img/ico/flutter.png"
      - name: "SQL"
        icon: "img/ico/sql.png"
      - name: "Firebase"
        icon: "img/ico/firebase.png"
      - name: "Big Querry"
        icon: "img/ico/big-query.png"
      - name: "Data Studio"
        icon: "img/ico/data-studio.png"
      - name: "G Cloud"
        icon: "img/ico/google-cloud.png"
    link: https://www.leconnecteur-biarritz.fr/
    id: connecteur
  # - date: "July 2021 - August 2021"
  #   company: "Boulanger SA"
  #   logo: "img/logo/boulanger.png"
  #   arrow: 50
  #   position: "TECHNICAL ADVISOR • Bayonne"
  #   description: "Advised clients for high-tech product purchases. Gained valuable insights into the world of sales and customer preferences."
  #   badges:
  #   id: boulanger
  - date: "Oct 2020 - Feb 2021"
    company: "Wellputt USA"
    logo: "img/logo/wellputt.png"
    arrow: 50
    position: "ANDROID DEVELOPER/PRODUCT OWNER • Freelance • Remote"
    description: "Spearheaded the development of an engaging Android application gamifying putting training, achieving a 4.9-star rating on the Play Store since the update and over 80,000 downloads."
    badges:
      - name: "Kotlin"
        icon: "img/ico/kotlin.png"
      - name: "Android"
        icon: "img/ico/android.png"
      - name: "Firebase"
        icon: "img/ico/firebase.png"
    id: wellputt
    link: https://play.google.com/store/apps/details?id=com.wellputt.wellputt
  - date: "July 2020 - August 2020"
    company: "Wellputt USA"
    logo: "img/logo/wellputt.png"
    arrow: 50
    position: "COMPUTER VISION ENGINEER • Freelance • Bayonne"
    description: "Led the development of a highly accurate golf ball tracking Computer Vision system and of a trajectory prediction algorithm for the Big Tilt platform."
    badges:
      - name: "C++"
        icon: "img/ico/cpp.png"
      - name: "Python"
        icon: "img/ico/python.png"
      - name: "Maplotlib"
        icon: "img/ico/matplotlib.png"
      - name: "Jupyter"
        icon: "img/ico/jupyter.png"
      - name: "Open CV"
        icon: "img/ico/open-cv.png"
      - name: "Pytorch"
        icon: "img/ico/pytorch.png"
    id: big_tilt
    link: https://wellputt.com/us/cms/10-bigtilt-concept
  - date: "May 2020 - July 2020"
    company: "Simbals"
    logo: "img/logo/simbals.png"
    arrow: 50
    position: "DATA SCIENTIST • Intern • Bordeaux"
    description: "Created innovative musical descriptors using Gradient Boosted Decision trees, providing musicians with new ways to discover music."
    badges:
      - name: "Python"
        icon: "img/ico/python.png"
      - name: "Catboost"
        icon: "img/ico/catboost.png"
      - name: "Maplotlib"
        icon: "img/ico/matplotlib.png"
      - name: "Jupyter"
        icon: "img/ico/jupyter.png"
      - name: "Librosa"
        icon: "img/ico/librosa.png"
      - name: "Pytorch"
        icon: "img/ico/pytorch.png"
    id: simbals
    link: https://www.simbals.com/
educations:
  - date: "Feb 2023 - July 2023"
    degree: "Exchange program"
    logo: "img/logo/KAIST.png"
    school: "Korean Advanced Institute of Science and Technology (KAIST)"
    description: "Participated in leading-edge projects at KAIST, widely regarded as the top engineering school in South Korea, known for its research-oriented focus."
    arrow: 50
    knowledges:
      - Deep Reinforcement Learning
      - Introduction to Autonomous Robotics
      - Graph Machine Learning
      - IOT Data Science
    link: https://www.kaist.ac.kr/en/html/kaist/01.html#0112

  - date: "Oct 2022 - Feb 2023"
    degree: "Exchange program"
    logo: "img/logo/TU_berlin.png"
    school: "Technical University Berlin"
    description: "Enrolled in courses on Brain-Computer Interfacing and Machine Learning, taught by renowned experts like Klaus-Robert Müller, one of the pioneers in the field."
    arrow: 50
    knowledges:
      - Machine Learning Theory 1
      - Python programming for Machine learning
      - Machine Intelligence 1
      - Brain Computer Interfacing
      - Reinforcement Learning Research Project (LIS Lab)
    link: https://www.tu.berlin/en/

  - date: "2020 - 2023"
    degree: "Engineer's degree in Computer Science - Artificial Intelligence Major - PhD track "
    logo: "img/logo/enseirb.png"
    school: "ENSEIRB-MATMECA - Bordeaux Graduate School in Electronics, Computer Science, Telecommunications, Mathematics and Mechanics"
    description: "Mastered the necessary theoretical and practical aspects of computer sciences. Joined the PhD track, which prepares engineering students for scientific research and its applications."
    arrow: 50
    knowledges:
      - Probability
      - Formal Methods
      - Functional Programing
      - Object Oriented Programing
      - Automata Theory
      - Compiler Theory
      - Quantum Computing
      - Numerical Methods
      - System Programming
      - Computability Theory
      - Robotics
      - Machine Learning

    link: https://enseirb-matmeca.bordeaux-inp.fr/fr/informatique
  - date: "2018 - 2020"
    degree: "Preparatory Class for the grandes ecoles"
    logo: "img/logo/prepa.png"
    school: "La Prepa des INP Bordeaux"
    description: "Two year high-intensity study of Mathematics and Physics to prepare for the entry into french engineering schools."
    arrow: 50
    knowledges:
      - Logic
      - Algebra
      - Differential Calculus
      - Group Theory
      - Numerical Sequences
      - Polynomials
      - Linear Algebra
      - Reduction of Endomorphisms
      - Thermodynamics
      - Classical Mechanics
      - Electrostatics and Magnetic Fields
      - Electric Circuits
      - Mecanical Waves
      - Fluid Mecanics
      - Wave Optics
      - Diffusion
      - Quantum Physics
  


projects:
  - date: "2023"
    name: "Dark Forest Reinforcement Learning"
    position: "TEAM LEAD"
    description: "Design and Implementation of Reinforcement Learning environment for modelling Inter-Solar system communication using DeepMind Melting pot, RLlib and Ray."
    badges:
    - name: "Lua"
      icon: "img/ico/lua.png"
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: "Deepmind Melting Pot"
      icon: "img/ico/deepmind.png"
    - name: "Docker"
      icon: "img/ico/docker.png"
    - name: "Ray"
      icon: "img/ico/ray.png"
    id: dark_forest
    link: https://www.overleaf.com/read/vsyjfssdqxyt
  - date: "2023"
    name: "Novel Dimensionality Reduction Technique using ML Graph Embeddings"
    position: "RESEARCHER"
    description: 'Developed and implemented a novel dimensionality reduction technique using Graph Embeddings to preserve data substructures effectively. The algorithm performed on par or better than the SOTA while being extremely simple.'
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: "Scikit-learn"
      icon: "img/ico/sklearn.png"
    id: dim_red
    link: https://drive.google.com/file/d/17jsUQMLpwazcbKq-TFzwzr73QORlgzHG/view?usp=sharing
  - date: "2023"
    name: "Remote controle AI based glove"
    position: "RESEARCHER"
    description: 'Assembled a glove covered in accelerometers and used Machine Learning to learn movements and recognize them using the arduino 33 BLE.'
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Tensorflow"
      icon: "img/ico/tensorflow.png"
    - name: "Arduino"
      icon: "img/ico/arduino.png"
    id: glove
    link: "https://youtu.be/p7Pj-NgkkpA"
  - date: "2023"
    name: "Gesture-Controlled Autonomous Drone for Group Photography"
    position: "DEVELOPER"
    description: 'Assembled and programmed a gesture-controlled autonomous quadcopter capable of capturing pictures of humans in different positions.'
    badges:
    - name: "C++"
      icon: "img/ico/cpp.png"
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Gazebo"
      icon: "img/ico/gazebo.png"
    - name: "ROS"
      icon: "img/ico/ros.png"
    - name: "Jetson Nano"
      icon: "img/ico/nvidia.png"

    link: https://pitch.com/public/dc243670-7bac-4cd7-addc-8ccf4bf6df14
    id: drone
  - date: "2022-2023"
    name: "Dreamer V2"
    position: "RESEARCHER"
    description: "Research on the effectiveness of the Dreamer V2 reinforcement learning algorithm in solving more complex puzzle-like tasks. Implementation of the algorithm, training on new tasks, and exploration of the algorithm's understanding of the tasks."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: ML Flow
      icon: "img/ico/ml-flow.png"
    id: dreamer_v2
    link: https://www.overleaf.com/read/mmwnsrzjkjbw
  - date: "2022"
    name: "Sim CLR Phd Track Project"
    position: "Team Member"
    description: "Conducted research on the effectiveness of the contrastive self-supervised learning method Sim-CLR on various datasets, and explored its performance on resource-constrained hardware."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Pytorch"
      icon: "img/ico/pytorch.png"
    - name: "Weights and Biases"
      icon: "img/ico/wb.svg"
    id: sim_clr
    link: https://www.overleaf.com/read/yckdhpynnftb
  - date: "2021"
    name: "IA Pau Data Challenge"
    position: "Team lead"
    description: "Lead a team of first-year students in the AI Data Challenge Pau, achieving the best performance and lowest training time on the patent classification task using fastText (Meta)."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "Fast Text"
      icon: "img/ico/fast-text.png"
    - name: "Qt"
      icon: "img/ico/qt.png"
    id: ai_data_challenge
    link: https://www.linkedin.com/posts/warisr_f%C3%A9licitations-%C3%A0-tous-les-membres-deirbia-activity-6893670431908253696-B9Lz?utm_source=share&utm_medium=member_desktop
  - date: "2021"
    name: "Walking Hexapod"
    position: "DEVELOPER"
    description: " Developed and implemented an efficient inverse kinematics and walking pattern for a 6-legged robot, demonstrating best in class precise and stable locomotion."
    badges:
    - name: "Python"
      icon: "img/ico/python.png"
    - name: "PyBullet"
      icon: "img/ico/py-bullet.png"
    id: hexapod
    # link: https://github.com/riiswa/colony-ant-simulator
skills:
  - icon: fas fa-robot
    category: Machine Learning
    content: Pytorch, TensorFlow, Scikit-learn, OpenCV, FastText, RLlib, DeepMind Melting Pot
  - icon: fas fa-code
    category: Programming
    content: Python, Java/Kotlin, Dart/Js, Swift, C/C++, Lua, Functional Programming
  - icon: fas fa-database
    category: Data Science
    content: Firebase, Big Query, Cloud Functions, Plotly, Matplotlib, Google Data Studio
  - icon: fas fa-globe
    category: Application Framework
    content: Flutter, Android, iOS, Web
  - icon: fas fa-robot
    category: Robotics
    content: RbPi/Jetson, Soldering, ROS, PyBullet, Gazebo, Orb-Slam

  # - icon: fas fa-chart-pie
  #   category: Data Visualization
  #   content: 
  - icon: fas fa-balance-scale
    category: Soft Skills
    content: Adaptability, Creativity, Problem-Solving, Attention to Detail, Team Spirit


